fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: cpplint
        args: 
          - --linelength=120
          - --filter=-legal/copyright

